apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  # Inbound connection details for the component (AKA endpoints)
  inbound:
    # Unique name for the endpoint. (This name will be used when generating the managed API)
    - name: GIG
      # Numeric port value that gets exposed via the endpoint
      port: 9000
      # Type of traffic that the endpoint is accepting. For example: REST, GraphQL, etc.
      # Allowed values: REST, GraphQL, GRPC, TCP, UDP.
      type: REST
      # Network level visibility of the endpoint. Defaults to Public
      # Accepted values: Project|Organization|Public.
      networkVisibility: Public
      # Context (base path) of the API that gets exposed via the endpoint.
      context: /
      # The path to the schema definition file. Defaults to wildcard route if not specified.
      # The path should be relative to the Docker context.
      schemaFilePath: docs/swagger.yaml